export function langCodeToString(langCode) {
    switch(langCode) {
        case "af":
            return "Afrikaans";
        case "sq":
            return "Albanian";
        case "am":
            return "Amharic";
        case "ar":
            return "Arabic";
        case "hy":
            return "Armenian";
        case "az":
            return "Azerbaijani";
        case "bn":
            return "Bengali";
        case "bs":
            return "Bosnian";
        case "bg":
            return "Bulgarian";
        case "ca":
            return "Catalan";
        case "zh":
            return "Chinese (Simplified)";
        case "zh-TW":
            return "Chinese (Traditional)";
        case "hr":
            return "Croatian";
        case "ca":
            return "Czech";
        case "da":
            return "Danish";
        case "fa-AF":
            return "Dari";
        case "nl":
            return "Dutch";
        case "en":
            return "English";
        case "et":
            return "Estonian";
        case "fa":
            return "Farsi (Persian)";
        case "tl":
            return "Filipino, Tagalog";
        case "fi":
            return "Finnish";
        case "fr":
            return "French";
        case "fr-CA":
            return "French (Canada)";
        case "ka":
            return "Georgian";
        case "de":
            return "German";
        case "el":
            return "Greek";
        case "gu":
            return "Gujarati";
        case "ht":
            return "Haitian Creole";
        case "ha":
            return "Hausa";
        case "he":
            return "Hebrew";
        case "hi":
            return "Hindi";
        case "hu":
            return "Hungarian";
        case "is":
            return "Icelandic";
        case "id":
            return "Indonesian";
        case "gg":
            return "Irish";
        case "it":
            return "Italian";
        case "ja":
            return "Japanese";
        case "kn":
            return "Kannada";
        case "kk":
            return "Kazakh";
        case "ko":
            return "Korean";
        case "lv":
            return "Latvian";
        case "lt":
            return "Lithuanian";
        case "mk":
            return "Macedonian";
        case "ms":
            return "Malay";
        case "ml":
            return "Malayalam";
        case "mt":
            return "Maltese";
        case "mr":
            return "Marathi";
        case "mn":
            return "Mongolian";
        case "no":
            return "Norwegian (Bokmål)";
        case "ps":
            return "Pashto";
        case "pl":
            return "Polish";
        case "pt":
            return "Portuguese (Brazil)";
        case "pt-PT":
            return "Portuguese (Portugal)";
        case "pa":
            return "Punjabi";
        case "ro":
            return "Romanian";
        case "ru":
            return "Russian";
        case "sr":
            return "Serbian";
        case "si":
            return "Sinhala";
        case "sk":
            return "Slovak";
        case "sl":
            return "Slovenian";
        case "so":
            return "Somali";
        case "es":
            return "Spanish";
        case "es-MX":
            return "Spanish (Mexico)";
        case "sw":
            return "Swahili";
        case "sv":
            return "Swedish";
        case "ta":
            return "Tamil";
        case "te":
            return "Telugu";
        case "th":
            return "Thai";
        case "tr":
            return "Turkish";
        case "uk":
            return "Ukrainian";
        case "ur":
            return "Urdu";
        case "uz":
            return "Uzbek";
        case "vi":
            return "Vietnamese";
        case "cy":
            return "Welsh";
    }
}